# spring 相关配置
spring:
  application:
    name: hypesphere-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/hypesphere_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        username: nacos
        password: nacos
      config:
        file-extension: yaml  # 明确指定文件扩展名
        server-addr: 127.0.0.1:8848
        group: dev  # 指定配置集的分组
        enabled: true
        username: nacos
        password: nacos
        namespace: hypesphere-product
  config:
    import: "optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}"   # 指定配置集Id
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai  # 或 GMT+8
    serialization:
      write-dates-as-timestamps: false  # 禁用时间戳格式

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0     # 逻辑已删除值
      logic-not-delete-value: 1 # 逻辑未删除值

# 服务
server:
  port: 8084

# 阿里云远程存储
alibaba:
  cloud:
    access-key: ${OSS_ACCESS_KEY_ID}
    secret-key: ${OSS_ACCESS_KEY_SECRET}
    oss:
      endpoint: oss-cn-qingdao.aliyuncs.com

# 日志级别
logging:
  level:
    com.elon.hypesphere: debug


