# spring 相关配置
spring:
  application:
    name: hypesphere-ware
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/hypesphere_wms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    sql:
      init:
        mode: always  # Spring Boot 3.x+ 使用此配置
        schema-locations: classpath:db/schema-mysql.sql  # 建表SQL
        data-locations: classpath:db/data-mysql.sql     # 初始数据SQL
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        username: nacos
        password: nacos
      config:
        file-extension: yaml  # 明确指定文件扩展名
        server-addr: 127.0.0.1:8848
        group: dev  # 指定配置集的分组
        enabled: true
        username: nacos
        password: nacos
        namespace: hypesphere-ware
  config:
    import: "optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}"   # 指定配置集Id
 # jackson相关配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai  # 或 GMT+8
    serialization:
      write-dates-as-timestamps: false  # 禁用时间戳格式

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

# 服务
server:
  port: 8085